version: '3.7'
networks:
  backend:
    name: app
    driver: bridge
volumes:
  postgres-data:
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: currency
    container_name: currency-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db
  db:
    image: library/postgres:12
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: pg_isready -U postgres
      interval: 1m
      timeout: 10s
      retries: 2